import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const kumbh_Sans = Kumbh_Sans({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbh_Sans.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
